version: '3'
services:
  public:
    build:
      context: .
      target: public
    ports:
      - 25565:25565
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "500k"
        max-file: "10"

  proxy-protocol:
    build:
      context: .
      target: proxy-protocol
    ports:
      - 60000:25565
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "500k"
        max-file: "10"

