FROM python:3 AS builder
ARG PROJECT='velocity'
ARG VERSION='3.1.1'

COPY ./requirements.txt ./fetch-paper-api.py /opt/fetch/
WORKDIR /opt/fetch
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN python fetch-paper-api.py $PROJECT $VERSION

#==============================================

FROM openjdk:17-alpine AS test
ENV TZ=Asia/Shanghai JAVA_MEMORY=256M
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
RUN apk update &&\
    apk add --no-cache tzdata python3

RUN mkdir /opt/velocity
WORKDIR /opt/velocity

RUN mkdir plugins
RUN mkdir logs

COPY --from=builder /opt/fetch/target.jar /opt/velocity/velocity.jar
COPY .  /opt/velocity/

ENTRYPOINT ["python", "main.py"]
