name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Build & Push Action
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image:  1ris/aisle-velocity
        # Tags override for Docker image
        # tags:  # optional
        # Target Docker registry
        registry: docker.io
        # Location of Dockerfile, if not Dockerfile in root directory
        # dockerfile: # optional, default is Dockerfile
        # Directory to run `docker build` from, if not project root
        # directory: # optional
        # Docker build arguments passed via --build-arg
        # buildArgs: # optional
        # Docker build labels passed via --label
        # labels: # optional
        # Docker build target passed via --target
        # target: # optional
        # Docker registry username
        username: ${{ secrets.DOCKER_USERNAME }} # optional
        # Docker registry password
        password: ${{ secrets.DOCKER_PASSWORD }} # optional
        # GitHub organization to push image to (if not current)
        # gitHubOrg: # optional
        # Adds latest tag to auto-generated GitOps tag
        addLatest: true # optional, default is false
        # Suffixes a build timestamp to the branch-based Docker tag
        # addTimestamp: # optional, default is false
